language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
install:
  - "pip install six"
  - "pip install unittest2"
  - "python setup.py install"
script: python setup.py test
notifications:
  # This branch fails to often for notifications to be useful.
  email: false
